export default {
    cart: [],
    buyer:[],
    total:0,
    productsFromLocalStorage:[],
    products: [
      {
        'id': '1',
        'image': 'https://i.ibb.co/s5phbkg/shoe-golden.png',
        'title': 'Camiseta',
        'price': 25,
        'quantity': 1,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit ',
      },
      {
        'id': '3',
        'image': 'https://i.ibb.co/s5phbkg/shoe-golden.png',
        'title': 'Mug',
        'price': 10,
        'quantity': 1,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '4',
        'image': 'https://i.ibb.co/s5phbkg/shoe-golden.png',
        'title': 'Pin',
        'price': 4,
        'quantity': 1,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '5',
        'image': 'https://i.ibb.co/s5phbkg/shoe-golden.png',
        'title': 'Stickers',
        'price': 2,
        'quantity': 1,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '6',
        'image': 'https://i.ibb.co/s5phbkg/shoe-golden.png',
        'title': 'Stickers',
        'price': 2,
        'quantity': 1,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '7',
        'image': 'https://i.ibb.co/s5phbkg/shoe-golden.png',
        'title': 'Hoodie',
        'price': 35,
        'quantity': 1,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
    ],
  };